### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by roobini-gamer** [MichaelZhao21/genshin-auto-checkin#1]
Not working anymore could you update it if that possible

**Comment by MichaelZhao21** [comment]
Not sure why this is happening to you as it still works on my end. I am currently running this script on a crontab instance on a Linux cloud server. One possible issue is that you are not running the script on an always-on machine (as your own computer may not run these tasks while hibernating or sleeping.

For me to look further into your inquiry, I will need information on the errors/output you are getting, as well as the system information that you are running the script on.

**Comment by MichaelZhao21** [comment]
Noticed an issue today where if you change your password, the token that you previously used will no longer work. This may be your issue, closing this issue for now due to inactivity.
